apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "eks-auth-iam-groups.fullname" . }}
  namespace: kube-system
  labels:
    {{- include "eks-auth-iam-groups.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "update"]
    resourceNames: ["aws-auth"]
