apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "eks-auth-iam-groups.fullname" . }}
  namespace: kube-system
  labels:
    {{- include "eks-auth-iam-groups.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "eks-auth-iam-groups.fullname" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "eks-auth-iam-groups.fullname" . }}
