apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eks-auth-iam-groups.fullname" . }}
  labels:
    {{- include "eks-auth-iam-groups.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if not (empty .Values.aws.accessKey) }}
  access-key: {{ .Values.aws.accessKey | b64enc | quote }}
  {{- end }}
  {{- if not (empty .Values.aws.secretKey) }}
  secret-key: {{ .Values.aws.secretKey | b64enc | quote }}
  {{- end }}
